print("*"*30)
name=input("Enter your name:")
print("NAME IS:", name)
print("*"*30)
age=input("Enter your age: ")
print("Age is : ", age)
print("*"*30)
number=input("Enter your phone no.:")
print("Mobile no. is :", number)
print("*"*30)
Email=input("Enter your email:")
print("Email is:", Email)
print("*"*30)
college=input("Enter college name:")
print("College is:", college)
print("*"*30)
Branch=input("Enter your branch:")
print("Branch is:",Branch )
print("*"*30)
message=input("Enter your message:")
print("Message is:",message)
print("*"*30)
username=input("Enter Username :")
print("Username is:",username)
print("*"*30)
password=input("Enter your password:")
print("Password is:",password)
print("*"*30)
course=input("Enter your course:")
print("Course is:",course)
print("*"*30)
favouritecar=input("Enter your favourite car name:")
print("Favourite car is:", favouritecar)
print("*"*30)
favouritefood=input("Enter your favourite food name:")
print("Favourite food is:", favouritefood)
print("*"*30)
favouritesong=input("Enter your favourite song name:")
print("Favourite song is:",favouritesong)
print("*"*30)
hobby=input("Enter your hobbies:")
print("Hobbies are:", hobby)
print("*"*30)
favouritemovie=input("Enter your favourite movie name:")
print("Favourite movie is:", favouritemovie)
print("*"*30)
favouritebike=input("Enter your favourite bike name:")
print("Favourite bike is:", favouritebike)
print("*"*30)
color=input("Enter color:")
print("Color is:",color)
print("*"*30)
shoebrand=input("Enter shoe brand:")
print("Shoe brand is:",shoebrand)
print("*"*30)
actor=input("Enter actor:")
print("Actor is:",actor)
print("*"*30)
mobilebrand=input("Enter mobile brand:")
print("Enter mobile brand:",mobilebrand)
print("*"*30)
pincode=input("Enter your pincode:")
print("Pincode is:",pincode)
print("*"*30)
salary=input("Enter your salary:")
print("Salary is:",salary)
print("*"*30)
DOB=input("Enter your DOB:")
print("DOB is:", DOB)
print("*"*30)
roomnumber=input("Enter your room no.:")
print("Romm no. is:", roomnumber)
print("*"*30)
ATMPIN=input("Enter your ATM pin:")
print("ATM pin is:", ATMPIN)
print("*"*30)
phoneprize=input("Enter your phone prize:")
print("Phone prize is:",phoneprize)
print("*"*30)
clothsize=input("Enter your cloth size:")
print("Cloth size is:",clothsize)
print("*"*30)
shoesize=input("Enter your shoe size:")
print("Shoe size is:",shoesize)
print("*"*30)
watch=input("Enter watch brand:")
print("Watch brand is:",watch)
print("*"*30)
time=input("Enter time:")
print("Time is:" ,time)
print("*"*30)
fruit=input("Enter fruit name:")
print("Fruit name is:", fruit)
print("*"*30)
vegetable=input("Enter vegetable name:")
print("Vegetable name is:", vegetable)
print("*"*30)
laptop=input("Enter your laptop brand:")
print("Laptop brand is:",laptop)
print("*"*30)
sweets=input("Enter Taste of sweet:")
print("Taste of sweet is:",sweets)
print("*"*30)
god=input("Enter Most powerful god name:")
print("Most powerful god is:",god)
print("*"*30)
mood=input("Enter your current mood:")
print("My current mood is:",mood)
print("*"*30)
house=input("Enter your house number:")
print("House number is:",house)
print("*"*30)
job=input("Enter your job name:")
print("Job name is:",job)
print("*"*30)
address=input("Enter your address:")
print("Address is:",address)
print("*"*30)
city=input("Enter your city name:")
print("City is:",city)
print("*"*30)
district=input("Enter your district name:")
print("District is:", district)
print("*"*30)
bank=input("Enter your bank name:")
print("Bank name is:",bank)
print("*"*30)
earth=input("Enter earth shape:")
print("Earth shape is:",earth)
print("*"*30)
sun=input("What is sun:")
print("Sun is a:",sun)
print("*"*30)
hair=input("Enter your hair color:")
print("Hair color is:",hair)
print("*"*30)
country=input("Enter country name:")
print("Country is:", country)
print("*"*30)
city=input("Enter your city name:")
print("City is:", city)
print("*"*30)
language=input("Enter your language:")
print("Language is:", language)
print("*"*30)
rollnumber=input("Enter your roll number:")
print("Roll number is:", rollnumber)
print("*"*30)
river=input("Enter river name:")
print("River name is:", river)
print("*"*30)
state=input("Enter your state name:")
print("State name is:", state)
print("*"*30)
game=input("Enter game name:")
print("Game name is:", game)